name: liquidity-model
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12
  - pandas==2.2.2
  - numpy==1.26.4
  - matplotlib==3.8.2
  - seaborn==0.13.2
  - scikit-learn==1.4.1.post1
  - imbalanced-learn==0.12.0
  - xgboost==2.0.3
  - setuptools>=68.0.0
  - wheel>=0.41.0
  - mlflow
  - onnxruntime
  - onnx
  - onnxmltools
  - skl2onnx
  - pip

